FROM openshift/origin-release:golang-1.9 as build
WORKDIR /go/src/github.com/coredns/coredns
ENV GOPATH=/go
COPY . .
RUN go build -o coredns .

FROM centos:7
COPY --from=build /go/src/github.com/coredns/coredns/coredns /usr/bin/coredns
